"NUCLEO-H7A3ZI-Q board"

flood_test.py result:
.
.
.
Received: DataCounter: 9
Received: DataCounter: 10
Received: DataCounter: 9
Received: DataCounter: 9
Received: DataCounter: 9
Received: DataCounter: 9
Received: DataCounter: 9
Received: DataCounter: 10
Received: DataCounter: 10
Received: DataCounter: 10
Received: DataCounter: 11
Received: DataCounter: 10
Received: DataCounter: 12
Received: DataCounter: 12
Received: DataCounter: 12
Received: DataCounter: 13
Received: DataCounter: 13
Received: DataCounter: 14
Received: DataCounter: 14
Received: DataCounter: 14
Received: DataCounter: 14
Received: DataCounter: 13
Received: DataCounter: 13
Received: DataCounter: 13
Received: DataCounter: 13
Received: DataCounter: 12
Received: DataCounter: 12
.
.
.
Flood test stopped...
...
Enter a command ('on' / 'off'): off
Command sent: OFF

The flood test continuously sends data to the microcontroller, 
with 20% of the data being invalid and 80% valid.
I ran the test for one minute, 
then verified the results using a simple command from user.py.